# Generated by Django 3.1.7 on 2021-04-09 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_str', models.TextField(max_length=50)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
