# Generated by Django 3.1.7 on 2021-04-08 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='files/uploads')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_str', models.TextField(max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='files/covers')),
            ],
        ),
    ]
