# Generated by Django 3.1.7 on 2021-04-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210406_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
